<?php
// Database Produk & Jasa Seluruh Jurusan SMKN 2 Karanganyar
$PRODUCTS_LIST = [
  // RPL (Digital: Download Otomatis & Lisensi)
  'rpl-1' => [
    'id' => 'rpl-1',
    'jurusan' => 'rpl',
    'jurusan_name' => 'Rekayasa Perangkat Lunak',
    'jurusan_link' => 'produk-rpl.php',
    'accent' => '#16a34a',
    'badge' => 'RPL • Digital',
    'status' => 'Download Otomatis',
    'category' => 'Software & Web App',
    'title' => 'Aplikasi E-Arsip Dokumen Sekolah v2.0',
    'desc' => 'Sistem informasi manajemen persuratan, disposisi digital, dan repositori arsip berkas sekolah lengkap dengan hak akses bertingkat untuk kepala sekolah, admin tata usaha, dan guru.',
    'full_desc' => 'Aplikasi E-Arsip Dokumen Sekolah v2.0 merupakan solusi digitalisasi administrasi persuratan yang dirancang oleh siswa TeFa RPL SMKN 2 Karanganyar. Sistem ini mampu mengelola surat masuk, surat keluar, nomor agenda otomatis, disposisi berjenjang dari kepala sekolah hingga staf, serta pencarian arsip berbasis OCR kata kunci. Dibangun menggunakan arsitektur PHP modern dan database MySQL yang ringan, aman, dan mudah di-deploy di web server lokal maupun cloud hosting.',
    'specs' => [
      'Full Source Code PHP & MySQL (Unencrypted)',
      'Database SQL & Schema Relasional Lengkap',
      'Manajemen Disposisi & Notifikasi Surat',
      'Pencarian Cepat & Filter Berdasarkan Tanggal',
      'Buku Panduan PDF & Video Instalasi',
      'Sertifikat Lisensi Resmi & Update 1 Tahun'
    ],
    'price' => 350000,
    'price_formatted' => 'Rp 350.000',
    'flow_type' => 'digital',
    'flow_note' => 'Download otomatis instan setelah pembayaran terkonfirmasi, dan Serial Key lisensi resmi dikirim ke email Anda.',
    'image' => '../images/3d-rpl.png'
  ],
  'rpl-2' => [
    'id' => 'rpl-2',
    'jurusan' => 'rpl',
    'jurusan_name' => 'Rekayasa Perangkat Lunak',
    'jurusan_link' => 'produk-rpl.php',
    'accent' => '#16a34a',
    'badge' => 'RPL • Digital',
    'status' => 'Download Otomatis',
    'category' => 'Website Template',
    'title' => 'Template Web Portofolio & Dashboard Modern',
    'desc' => 'Desain antarmuka template siap pakai dengan tampilan modern, responsive di semua ukuran layar smartphone dan tablet, dilengkapi dark mode, serta animasi micro-interaction halus.',
    'full_desc' => 'Template antarmuka website serbaguna dengan komponen UI modern berbasis standar web terkini. Sangat cocok untuk website portofolio agensi, dashboard monitoring, profil perusahaan, maupun aplikasi SaaS startup. Memiliki skor performa Google PageSpeed 98+, struktur semantik SEO ramah mesin pencari, dan integrasi ikon yang rapi.',
    'specs' => [
      'HTML5, Modern CSS & Vanilla JavaScript',
      '5 Varian Layout Halaman Siap Pakai',
      'Dukungan Mode Terang & Gelap (Dark Mode)',
      'Source File Desain Figma Komponen Lengkap',
      'Struktur Clean Code & Mudah Dikustomisasi'
    ],
    'price' => 125000,
    'price_formatted' => 'Rp 125.000',
    'flow_type' => 'digital',
    'flow_note' => 'Download otomatis instan setelah pembayaran terkonfirmasi, dan Serial Key lisensi resmi dikirim ke email Anda.',
    'image' => '../images/3d-rpl.png'
  ],
  'rpl-3' => [
    'id' => 'rpl-3',
    'jurusan' => 'rpl',
    'jurusan_name' => 'Rekayasa Perangkat Lunak',
    'jurusan_link' => 'produk-rpl.php',
    'accent' => '#16a34a',
    'badge' => 'RPL • Digital',
    'status' => 'Download Otomatis',
    'category' => 'Desain Grafis & UI Kit',
    'title' => 'Master UI/UX Kit & Desain Grafis Sekolah',
    'desc' => 'Koleksi komponen UI aplikasi mobile edukasi format Figma, bundle ilustrasi vektor SVG sekolah, maskot jurusan, dan 100+ icon pack berlisensi komersial bebas royalti.',
    'full_desc' => 'Paket aset desain grafis dan UI/UX mobile yang dirancang dengan grid sistematis 8pt. Berisi ratusan varian button, kartu, form input, modal dialog, icon set vektor, serta ilustrasi maskot edukasi. Siap pakai untuk mahasiswa, developer frontend, dan desainer produk digital untuk mempercepat waktu pengembangan aplikasi.',
    'specs' => [
      'Figma Component Library (Auto-Layout v5)',
      '100+ Vector Icons (.SVG, .PNG transparan)',
      'Bundle Ilustrasi Vektor Tema Sekolah & Vokasi',
      'Desain Sistem Warna & Skala Tipografi',
      'Lisensi Komersial Bebas Royalti Seumur Hidup'
    ],
    'price' => 90000,
    'price_formatted' => 'Rp 90.000',
    'flow_type' => 'digital',
    'flow_note' => 'Download otomatis instan setelah pembayaran terkonfirmasi, dan Serial Key lisensi resmi dikirim ke email Anda.',
    'image' => '../images/3d-rpl.png'
  ],
  'rpl-4' => [
    'id' => 'rpl-4',
    'jurusan' => 'rpl',
    'jurusan_name' => 'Rekayasa Perangkat Lunak',
    'jurusan_link' => 'produk-rpl.php',
    'accent' => '#16a34a',
    'badge' => 'RPL • Jasa TeFa',
    'status' => 'Kontrak Resmi',
    'category' => 'Software House TeFa',
    'title' => 'Jasa Pembuatan Web Profil / Landing Page Custom',
    'desc' => 'Layanan pengerjaan website profil sekolah, UMKM, instansi, atau portofolio bisnis yang digarap langsung oleh tim siswa berbakat RPL di bawah supervisi guru praktisi industri.',
    'full_desc' => 'Teaching Factory RPL membuka jasa pembuatan website profesional custom sesuai kebutuhan klien. Alur pengerjaan mencakup wawancara kebutuhan sistem, perancangan mockup UI/UX di Figma, pengkodean backend & frontend, hingga deployment online di domain Anda. Dikelola profesional dengan kontrak kerja dan masa garansi pemeliharaan.',
    'specs' => [
      'Desain Unik & Custom Sesuai Brand Klien',
      'Responsive Mobile & Tablet Friendly',
      'Optimalisasi Kecepatan & SEO On-Page',
      'Termasuk Domain .com / .sch.id & Hosting 1 Th',
      'Garansi Pemeliharaan Bug Selama 3 Bulan'
    ],
    'price' => 750000,
    'price_formatted' => 'Rp 750.000',
    'flow_type' => 'digital',
    'flow_note' => 'Konsultasi spesifikasi pengerjaan, penerbitan kontrak resmi TeFa, dan pengiriman akses admin via email.',
    'image' => '../images/3d-rpl.png'
  ],

  // TEKSTIL (Fisik: Kurir / Ekspedisi / Ambil di TeFa)
  'tekstil-1' => [
    'id' => 'tekstil-1',
    'jurusan' => 'tekstil',
    'jurusan_name' => 'Teknik Pembuatan Kain',
    'jurusan_link' => 'produk-tekstil.php',
    'accent' => '#ea580c',
    'badge' => 'Tekstil • Seragam',
    'status' => 'Ready Stock / PO',
    'category' => 'Pakaian Kerja & Seragam',
    'title' => 'Seragam Praktik / Wearpack Standar Industri',
    'desc' => 'Baju praktik wearpack berbahan American Drill grade A tebal, tahan robek, nyaman dipakai di bengkel, dilengkapi jahitan rantai ganda, pita scotchlite reflektif keselamatan, serta bordir komputer presisi.',
    'full_desc' => 'Wearpack baju praktik standar keselamatan kerja bengkel teknik (K3). Menggunakan material kain American Drill pilihan yang tidak panas, menyerap keringat, dan tahan gesekan mekanik. Dilengkapi 4 saku fungsional, resleting tertutup pelindung, serta pita pemantul cahaya scotchlite 3M untuk keamanan optimal saat beraktivitas di bengkel kerja.',
    'specs' => [
      'Bahan American Drill Grade A (Tahan Robek)',
      'Tersedia Ukuran S, M, L, XL, XXL',
      'Scotchlite Reflektif Keselamatan Standar K3',
      'Jahitan Rantai Ganda & Resleting Logam Awet',
      'Bordir Komputer Logo Sekolah / Custom Nama'
    ],
    'price' => 185000,
    'price_formatted' => 'Rp 185.000',
    'flow_type' => 'fisik',
    'flow_note' => 'Pilihan pengiriman via Kurir Lokal, Ekspedisi Reguler (JNE/J&T), atau diambil langsung di Teaching Factory Gedung B.',
    'image' => '../images/3d-tekstil.png'
  ],
  'tekstil-2' => [
    'id' => 'tekstil-2',
    'jurusan' => 'tekstil',
    'jurusan_name' => 'Teknik Pembuatan Kain',
    'jurusan_link' => 'produk-tekstil.php',
    'accent' => '#ea580c',
    'badge' => 'Tekstil • Tas Tenun',
    'status' => 'Ready Stock',
    'category' => 'Tas & Aksesoris',
    'title' => 'Tas Totebag Tenun Etnik Motif Lawu',
    'desc' => 'Totebag berkelas menggabungkan kain tenun asli karya mesin pertenunan TeFa dengan kanvas katun kokoh. Dilengkapi lapisan furing halus, kantong dalam, serta resleting logam kuat.',
    'full_desc' => 'Totebag etnik modern yang memadukan kain tenun asli hasil produksi mesin pertenunan rapier dan ATBM SMKN 2 Karanganyar dengan bahan kanvas katun tebal. Dirancang kuat menampung beban hingga 10 kg, memiliki kompartemen khusus laptop 14 inchi dengan bantalan empuk, serta saku kecil beresleting untuk kunci dan smartphone.',
    'specs' => [
      'Kain Tenun Pertenunan Asli Siswa TeFa',
      'Bahan Dasar Kanvas Katun Tebal 12 Oz',
      'Kompartemen Muat Laptop Hingga 14 Inchi',
      'Lapisan Furing Dalam Tahan Percikan Air',
      'Tali Webbing Tebal & Jahitan Bar-tack Kuat'
    ],
    'price' => 65000,
    'price_formatted' => 'Rp 65.000',
    'flow_type' => 'fisik',
    'flow_note' => 'Pilihan pengiriman via Kurir Lokal, Ekspedisi Reguler (JNE/J&T), atau diambil langsung di Teaching Factory Gedung B.',
    'image' => '../images/3d-tekstil.png'
  ],
  'tekstil-3' => [
    'id' => 'tekstil-3',
    'jurusan' => 'tekstil',
    'jurusan_name' => 'Teknik Pembuatan Kain',
    'jurusan_link' => 'produk-tekstil.php',
    'accent' => '#ea580c',
    'badge' => 'Tekstil • Printing',
    'status' => 'Ready Stock',
    'category' => 'Fashion & Printing',
    'title' => 'Syal & Hijab Printing Motif Khas Karanganyar',
    'desc' => 'Hijab segi empat dan syal leher berbahan voal ultrafine lembut dan adem. Dicetak menggunakan tinta ramah lingkungan dengan motif orisinil tanaman teh dan lereng Gunung Lawu.',
    'full_desc' => 'Syal dan kerudung hijab premium dengan teknik printing digital tekstil mutakhir. Motif karya kreasi siswa menggambarkan keindahan alam lereng Gunung Lawu dan perkebunan teh Kemuning. Memiliki handfeel yang sangat lembut di kulit, mudah dibentuk, tidak licin, serta tepian kain diproses rapi dengan teknologi laser cut modern tanpa benang bertiras.',
    'specs' => [
      'Ukuran Standar 115 x 115 cm',
      'Bahan Voal Ultrafine Premium (Adem & Lembut)',
      'Tinta Cetak Ramah Lingkungan Standar OEKO-TEX',
      'Finishing Tepi Laser-Cut Rapi & Presisi',
      'Termasuk Box Kemasan Eksklusif'
    ],
    'price' => 45000,
    'price_formatted' => 'Rp 45.000',
    'flow_type' => 'fisik',
    'flow_note' => 'Pilihan pengiriman via Kurir Lokal, Ekspedisi Reguler (JNE/J&T), atau diambil langsung di Teaching Factory Gedung B.',
    'image' => '../images/3d-tekstil.png'
  ],
  'tekstil-4' => [
    'id' => 'tekstil-4',
    'jurusan' => 'tekstil',
    'jurusan_name' => 'Teknik Pembuatan Kain',
    'jurusan_link' => 'produk-tekstil.php',
    'accent' => '#ea580c',
    'badge' => 'Tekstil • Aksesoris',
    'status' => 'Ready Stock',
    'category' => 'Souvenir & Kerajinan',
    'title' => 'Pouch & Dompet Tenun Serbaguna',
    'desc' => 'Pouch multifungsi untuk menyimpan alat tulis sekolah, kosmetik, kabel charger, maupun gadget kecil, diproduksi dari kain tenun berkualitas dengan bantalan busa pelindung.',
    'full_desc' => 'Dompet pouch serbaguna bertekstur tenun tradisional. Cocok digunakan sebagai tempat pensil, pouch kosmetik wanita, atau organizer kabel gadget saat bepergian. Bagian dalam dilapisi furing halus dengan busa penahan benturan ringan agar barang di dalamnya aman.',
    'specs' => [
      'Dimensi Ukuran 22 x 14 cm',
      'Aksen Kain Tenun Pertenunan Asli',
      'Bantalan Busa Inner Penahan Benturan',
      'Resleting Logam YKK Halus & Awet'
    ],
    'price' => 30000,
    'price_formatted' => 'Rp 30.000',
    'flow_type' => 'fisik',
    'flow_note' => 'Pilihan pengiriman via Kurir Lokal, Ekspedisi Reguler (JNE/J&T), atau diambil langsung di Teaching Factory Gedung B.',
    'image' => '../images/3d-tekstil.png'
  ],

  // MESIN (Manufaktur: Suku Cadang Fisik & Jasa Bubut / Servis)
  'mesin-1' => [
    'id' => 'mesin-1',
    'jurusan' => 'mesin',
    'jurusan_name' => 'Teknik Mesin',
    'jurusan_link' => 'produk-mesin.php',
    'accent' => '#2563eb',
    'badge' => 'Mesin • Sparepart',
    'status' => 'Ready Stock',
    'category' => 'Manufaktur & Suku Cadang',
    'title' => 'Suku Cadang Presisi Bushing & Flange Kuningan/Baja',
    'desc' => 'Komponen permesinan silindris presisi tinggi hasil pengerjaan mesin bubut konvensional dan CNC dengan toleransi ukuran mikrometer standar industri manufaktur untuk kebutuhan mesin produksi.',
    'full_desc' => 'Komponen suku cadang mesin industri kecil hingga menengah yang diproduksi dengan mesin bubut CNC presisi. Melalui tahapan facing, turning, boring, dan finishing halus dengan toleransi dimensi hingga ±0.02 mm. Setiap batch produk diuji dimensi menggunakan mikrometer sekrup dan dial bore gauge terkalibrasi.',
    'specs' => [
      'Pilihan Material Kuningan CuZn39Pb3 / Baja St42',
      'Toleransi Dimensi Ketat Presisi ±0.02 mm',
      'Permukaan Halus Ra 0.8 Hasil Turning Halus',
      'Inspeksi Quality Control Lolos Uji Dimensi',
      'Melayani Pesanan Satuan Maupun Partai Batch'
    ],
    'price' => 55000,
    'price_formatted' => 'Rp 55.000',
    'flow_type' => 'fisik',
    'flow_note' => 'Pilihan pengiriman via ekspedisi atau diambil langsung di Bengkel Mesin TeFa Gedung B.',
    'image' => '../images/3d-mesin.png'
  ],
  'mesin-2' => [
    'id' => 'mesin-2',
    'jurusan' => 'mesin',
    'jurusan_name' => 'Teknik Mesin',
    'jurusan_link' => 'produk-mesin.php',
    'accent' => '#2563eb',
    'badge' => 'Mesin • Ornamen',
    'status' => 'Pre-Order 3 Hari',
    'category' => 'Ornamen Logam & Fabrikasi',
    'title' => 'Ornamen Papan Nama Stainless Metal Laser Cutting',
    'desc' => 'Papan nama meja kantor, plakat penghargaan, dan ornamen hiasan dinding berbahan plat stainless steel 304 anti karat yang dipotong presisi dengan tepi halus dan tampilan elegan mengkilap.',
    'full_desc' => 'Produk dekorasi interior dan papan identitas kantor berkualitas premium berbahan plat stainless steel 304 tahan karat. Pemotongan pola teks dan logo dikerjakan dengan mesin CNC laser cutting sehingga hasil sudut tajam, presisi, dan bebas burr tajam. Pilihan finishing permukaan mengkilap (mirror) atau garis serat halus (hairline).',
    'specs' => [
      'Material Plat Stainless Steel 304 Anti Karat',
      'Ketebalan Plat 1.5 mm - 2.0 mm',
      'Kustomisasi Huruf, Kaligrafi, & Logo Instansi',
      'Finishing Hairline Brushed / Mirror Polished',
      'Termasuk Baut Pen Stainless & Fisher Dinding'
    ],
    'price' => 150000,
    'price_formatted' => 'Rp 150.000',
    'flow_type' => 'fisik',
    'flow_note' => 'Pengerjaan Pre-Order 3 hari kerja, dikirim via ekspedisi atau diambil di TeFa.',
    'image' => '../images/3d-mesin.png'
  ],
  'mesin-3' => [
    'id' => 'mesin-3',
    'jurusan' => 'mesin',
    'jurusan_name' => 'Teknik Mesin',
    'jurusan_link' => 'produk-mesin.php',
    'accent' => '#2563eb',
    'badge' => 'Mesin • Jasa Bubut',
    'status' => 'Workshop TeFa',
    'category' => 'Jasa Bengkel & Permesinan',
    'title' => 'Jasa Bubut & Fabrikasi Las Kustom Gambar Kerja',
    'desc' => 'Layanan pengerjaan pembubutan poros as, perbaikan ulir draad rusak, dan perakitan rangka besi/baja dengan teknik las TIG, MIG, dan SMAW sesuai cetak biru pesanan pelanggan.',
    'full_desc' => 'Bengkel TeFa Mesin SMKN 2 Karanganyar melayani pengerjaan teknik pesanan kustom dari masyarakat umum maupun industri rekanan. Meliputi perataan bidang silinder, pembuatan alur pasak, penyambungan rangka dengan las argon (TIG) dan CO2 (MIG) berkekuatan tinggi, serta pembuatan alat bantu produksi.',
    'specs' => [
      'Pengerjaan Sesuai Gambar Kerja (Blueprint)',
      'Mesin Bubut Konvensional & CNC Milling',
      'Pengelasan TIG (Argon), MIG (CO2), & SMAW',
      'Konsultasi Pemilihan Bahan Logam Gratis',
      'Dikerjakan Teknisi Berpengalaman & Siswa TeFa'
    ],
    'price' => 75000,
    'price_formatted' => 'Rp 75.000 (Mulai)',
    'flow_type' => 'booking',
    'flow_note' => 'Konsultasikan gambar kerja di bengkel, jadwalkan waktu pengerjaan, dan bayar setelah hasil pengerjaan selesai.',
    'image' => '../images/3d-mesin.png'
  ],
  'mesin-4' => [
    'id' => 'mesin-4',
    'jurusan' => 'mesin',
    'jurusan_name' => 'Teknik Mesin',
    'jurusan_link' => 'produk-mesin.php',
    'accent' => '#2563eb',
    'badge' => 'Mesin • Servis Mesin',
    'status' => 'Jasa Servis',
    'category' => 'Pemeliharaan & Rekondisi',
    'title' => 'Jasa Servis & Rekondisi Mesin Perkakas Bengkel',
    'desc' => 'Layanan perbaikan dan kalibrasi mesin perkakas industri ringan, meliputi penggantian bearing transmisi gear head, perataan meja mesin milling, perbaikan lead screw, dan alignment sumbu spindle.',
    'full_desc' => 'Layanan pemeliharaan dan perbaikan preventif maupun korektif untuk mesin perkakas bengkel produksi (bubut, milling, shaping, bor duduk). Tim kami menangani masalah getaran tidak wajar, poros spindle oleng, keausan roda gigi transmisi, serta rekondisi sistem pelumasan mesin agar kembali presisi dan optimal.',
    'specs' => [
      'Inspeksi Awal & Pengecekan Runout Spindle',
      'Penggantian Bantalan (Bearing) Presisi',
      'Perbaikan Mekanisme Eretan & Lead Screw',
      'Penyetelan Alignment & Kerataan Meja',
      'Garansi Uji Coba Pengerjaan Pasca Servis'
    ],
    'price' => 200000,
    'price_formatted' => 'Rp 200.000 (Mulai)',
    'flow_type' => 'booking',
    'flow_note' => 'Booking jadwal kedatangan inspeksi mesin, pengerjaan di workshop, dan bayar di kasir setelah servis selesai.',
    'image' => '../images/3d-mesin.png'
  ],

  // OTOTRONIK (Layanan Servis & Booking Appointment)
  'oto-1' => [
    'id' => 'oto-1',
    'jurusan' => 'ototronik',
    'jurusan_name' => 'Teknik Ototronik',
    'jurusan_link' => 'produk-ototronik.php',
    'accent' => '#dc2626',
    'badge' => 'Ototronik • Motor',
    'status' => 'Slot Tersedia',
    'category' => 'Bengkel Servis TeFa',
    'title' => 'Servis Berkala & Tune-Up Injeksi Sepeda Motor',
    'desc' => 'Perawatan menyeluruh sistem bahan bakar injeksi, pembersihan injector dan throttle body, reset ECU scanner, pengecekan busi, filter udara, sistem pengereman, rantai roda, serta penggantian oli mesin.',
    'full_desc' => 'Layanan tune-up lengkap untuk semua jenis sepeda motor bebek dan matic (Honda, Yamaha, Suzuki, Kawasaki). Menggunakan cairan injector cleaner khusus untuk membersihkan kerak ruang bakar dan throttle body. Melakukan reset data sensor ECU dan kalibrasi putaran stasioner mesin agar tarikan responsif kembali dan konsumsi bahan bakar irit.',
    'specs' => [
      'Pembersihan Throttle Body & Injector Cairan Khusus',
      'Reset Sensor & Kalibrasi Data ECU Komputer',
      'Pengecekan Busi, Filter Udara, & Setel Celah Klep',
      'Pemeriksaan Sistem Rem Depan-Belakang & Rantai',
      'Pengecekan Kelistrikan & Estimasi Waktu 45 Menit'
    ],
    'price' => 45000,
    'price_formatted' => 'Rp 45.000',
    'flow_type' => 'booking',
    'flow_note' => 'Sistem Booking Jadwal (Appointment): Pesan slot online, datang ke sekolah, lalu bayar di kasir setelah servis selesai (Tanpa DP).',
    'image' => '../images/3d-oto.png'
  ],
  'oto-2' => [
    'id' => 'oto-2',
    'jurusan' => 'ototronik',
    'jurusan_name' => 'Teknik Ototronik',
    'jurusan_link' => 'produk-ototronik.php',
    'accent' => '#dc2626',
    'badge' => 'Ototronik • Mobil',
    'status' => 'Slot Tersedia',
    'category' => 'Diagnostik Komputer Mobil',
    'title' => 'Scan ECU Komputer Mobil & Diagnostik OBD-II',
    'desc' => 'Deteksi akurat kerusakan sensor kendaraan menggunakan scanner komputer mutakhir, pembacaan live data mesin, penghapusan kode kerusakan error check engine (DTC), dan kalibrasi parameter kontrol mobil cerdas.',
    'full_desc' => 'Layanan pemindaian komputer cerdas mobil segala merek (Toyota, Daihatsu, Honda, Mitsubishi, Suzuki, Nissan, dll) menggunakan scanner otomotif multi-brand OBD-II. Mampu mendeteksi secara presisi sensor yang bermasalah (O2 sensor, MAF, TPS, CKP), membaca temperatur mesin dan rasio bahan bakar secara real-time, serta mematikan lampu indikator check engine yang menyala.',
    'specs' => [
      'Scanner Komputer Diagnostik OBD-II Multi-Brand',
      'Pembacaan Live Data Parameter Mesin Real-Time',
      'Deteksi & Penghapusan Kode Kerusakan (DTC Reset)',
      'Kalibrasi Throttle Adaptasi & Uji Aktuator',
      'Lembar Printout Laporan Hasil Diagnosa Mesin'
    ],
    'price' => 120000,
    'price_formatted' => 'Rp 120.000',
    'flow_type' => 'booking',
    'flow_note' => 'Sistem Booking Jadwal (Appointment): Pesan slot online, datang ke sekolah, lalu bayar di kasir setelah servis selesai (Tanpa DP).',
    'image' => '../images/3d-oto.png'
  ],
  'oto-3' => [
    'id' => 'oto-3',
    'jurusan' => 'ototronik',
    'jurusan_name' => 'Teknik Ototronik',
    'jurusan_link' => 'produk-ototronik.php',
    'accent' => '#dc2626',
    'badge' => 'Ototronik • AC Mobil',
    'status' => 'Slot Tersedia',
    'category' => 'Sistem Pendingin Kendaraan',
    'title' => 'Servis AC Mobil & Penggantian Freon Otomatis',
    'desc' => 'Pemeriksaan kebocoran sirkulasi pipa freon, kuras oli kompresor dengan mesin flushing otomatis, pengisian freon murni R134a, uji suhu evaporator kabin, serta penggantian filter AC agar udara kabin segar dingin.',
    'full_desc' => 'Perawatan sistem pendingin kabin mobil menggunakan mesin AC Recovery & Flushing otomatis. Mesin ini menguras oli kompresor lama yang telah kotor, memvakum sirkulasi pipa untuk menguji kebocoran, menyuntikkan oli kompresor sintetik baru, dan mengisi takaran gas freon R134a murni sesuai spesifikasi pabrikan kendaraan.',
    'specs' => [
      'Mesin Otomatis Recovery, Vakum, & Oli Flushing',
      'Pengisian Freon Murni Standar R134a Presisi Gram',
      'Pengujian Suhu Udara Grill Evaporator Kabin',
      'Pengecekan Kebocoran Tekanan Tinggi & Rendah',
      'Pembersihan / Penggantian Filter Blower Kabin'
    ],
    'price' => 150000,
    'price_formatted' => 'Rp 150.000',
    'flow_type' => 'booking',
    'flow_note' => 'Sistem Booking Jadwal (Appointment): Pesan slot online, datang ke sekolah, lalu bayar di kasir setelah servis selesai (Tanpa DP).',
    'image' => '../images/3d-oto.png'
  ],
  'oto-4' => [
    'id' => 'oto-4',
    'jurusan' => 'ototronik',
    'jurusan_name' => 'Teknik Ototronik',
    'jurusan_link' => 'produk-ototronik.php',
    'accent' => '#dc2626',
    'badge' => 'Ototronik • Kelistrikan',
    'status' => 'Slot Tersedia',
    'category' => 'Kelistrikan Bodi & Baterai',
    'title' => 'Perawatan Kelistrikan Bodi & Cek Baterai Aki',
    'desc' => 'Pemeriksaan kondisi kesehatan baterai aki dengan digital conductance tester, pengecekan pengisian dinamo alternator, pembersihan kutub baterai, dan perbaikan instalasi sistem lampu serta klakson.',
    'full_desc' => 'Layanan perawatan kelistrikan komprehensif untuk memastikan kendaraan Anda tidak mogok akibat masalah baterai aki atau pengisian alternator. Menggunakan digital battery analyzer untuk mengukur persentase State of Health (SOH) dan Cold Cranking Amps (CCA), serta memeriksa kinerja regulator sekring dan relay lampu.',
    'specs' => [
      'Digital Battery Tester (Cek CCA & Health %)',
      'Pemeriksaan Tegangan Pengisian Dinamo Alternator',
      'Pembersihan Korosi Kerak Terminal Kutub Aki',
      'Pemeriksaan Beban Sistem Lampu, Klakson & Sekring',
      'Estimasi Pengerjaan Cepat Sekitar 30 Menit'
    ],
    'price' => 35000,
    'price_formatted' => 'Rp 35.000',
    'flow_type' => 'booking',
    'flow_note' => 'Sistem Booking Jadwal (Appointment): Pesan slot online, datang ke sekolah, lalu bayar di kasir setelah servis selesai (Tanpa DP).',
    'image' => '../images/3d-oto.png'
  ]
];
